.TH NICOTINE 1 "October 2006" "Version 1.2.6"

.SH NAME
.B nicotine
is a graphical client for the SoulSeek peer-to-peer network.
.SH SYNOPSIS
.B nicotine
[options]
.SH DESCRIPTION
.BI nicotine
is a GTK-based client for the SoulSeek peer-to-peer network written in Python.
.SH OPTIONS
.TP
.I -h, --help
Show help and exit.
.TP
.I -c <file>, --config=<file>
Use <file> as configuration file. If <file> do not exists a new empty configuration file will be created.
.SH AUTHOR
This manual page was written by Adam Cecile <gandalf@le-vert.net> for the Nicotine+ project.
.br
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.
.SH SEE ALSO
.B nicotine-import-winconfig(1)
