name: nicotine
adopt-info: nicotine
license: GPL-3.0+

base: core22
confinement: strict
compression: lzo

apps:
  nicotine:
    environment:
      SNAPCRAFT_PRELOAD_REDIRECT_ONLY_SHM: 1
    command: bin/snapcraft-preload python3 -m pynicotine
    common-id: org.nicotine_plus.Nicotine
    desktop: share/applications/org.nicotine_plus.Nicotine.desktop
    extensions: [gnome]
    plugs:
      - network
      - network-bind

parts:
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib
  nicotine:
    plugin: python
    source: .
    parse-info: [share/metainfo/org.nicotine_plus.Nicotine.appdata.xml]
    override-pull: |
      craftctl default
      sed -E 's|Icon=.*|Icon=snap.$CRAFT_PROJECT_NAME.org.nicotine_plus.Nicotine|' -i data/org.nicotine_plus.Nicotine.desktop.in
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp -r $CRAFT_PART_INSTALL/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done

slots:
  nicotine:
    interface: dbus
    bus: session
    name: org.nicotine_plus.Nicotine
