.\"                                      Hey, EMACS: -*- nroff -*-
.TH NICOTINE 1 "August 25, 2003"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
nicotine \- client for the SoulSeek peer-to-peer sharing system
.SH DESCRIPTION
This manual page documents briefly the
.B nicotine
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
\fBnicotine\fP is a graphical client for the \fISoulSeek\fP filesharing
network. It is designed to be fairly simple to use; right-clicking
on an item in any list gives you the menu of what's available.
.PP
To search for files, just enter your search string into the input box in 
the search tab.
.SH SEE ALSO
.IR /usr/share/doc/nicotine/ .
.SH AUTHOR
This manual page was written by Josselin Mouette <joss@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
