# SPDX-FileCopyrightText: 2020-2025 Nicotine+ Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: Packaging
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      create_release:
        description: Create new release
        type: boolean
        required: false

permissions: {}

jobs:
  python-dist:
    runs-on: ubuntu-slim
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install gettext python3-build

      - name: Build package
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: python-dist
          path: dist/

  debian:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-build
          sudo apt build-dep .

      - name: Build Debian package
        run: |
          python3 -m build --sdist --no-isolation
          mk-origtargz dist/nicotine-plus-*.tar.gz
          debuild -sa -us -uc

      - name: Prepare artifacts
        run: |
          mkdir build/package/
          cp -Lr ../nicotine_* build/package/

      - name: Archive artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: debian-package
          path: build/package/

  flatpak:
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - arch: x86_64
            platform: ubuntu-latest
          - arch: aarch64
            platform: ubuntu-24.04-arm
    runs-on: ${{ matrix.platform }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Validate manifest
        run: flatpak-builder-lint --exceptions manifest build-aux/flatpak/org.nicotine_plus.Nicotine.json

      - name: Validate appstream
        run: flatpak-builder-lint appstream data/org.nicotine_plus.Nicotine.appdata.xml.in

      - name: Build Flatpak package
        run: |
          flatpak-builder \
            --repo=repo \
            --disable-download \
            --disable-rofiles-fuse \
            --force-clean \
            flatpak_app build-aux/flatpak/org.nicotine_plus.Nicotine.json

          flatpak build-bundle repo \
            org.nicotine_plus.Nicotine-${{ matrix.arch }}.flatpak \
            --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo \
            org.nicotine_plus.Nicotine

      - name: Archive artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: flatpak-${{ matrix.arch }}-package
          path: org.nicotine_plus.Nicotine-${{ matrix.arch }}.flatpak

  snap:
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - arch: x86_64
            platform: ubuntu-latest
          - arch: arm64
            platform: ubuntu-24.04-arm
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Snapcraft
        run: |
          sudo usermod --append --groups lxd "$USER"
          sudo snap install lxd
          sudo lxd init --auto
          sudo iptables -P FORWARD ACCEPT
          sudo snap install --classic snapcraft

      - name: Build Snap package
        run: sudo -u "$USER" -E snapcraft pack

      - name: Install Snap package
        run: sudo snap install --dangerous nicotine-plus_*.snap

      - name: Archive artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: snap-${{ matrix.arch }}-package
          path: nicotine-plus_*.snap

  appimage:
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - arch: x86_64
            platform: ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Miniforge
        run: |
          wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
          bash "Miniforge3-$(uname)-$(uname -m).sh" -b -p "$HOME/miniforge3"
          echo "$HOME/miniforge3/bin" >> "$GITHUB_PATH"

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install --no-install-recommends cage file fuse

          mamba create -n nicotine-plus
          mamba create -n startup-test
          mamba run -n nicotine-plus python3 build-aux/appimage/dependencies.py

      - name: Freeze application
        run: mamba run -n nicotine-plus python3 build-aux/appimage/setup.py bdist_appimage

      - name: Test application startup
        run: |
          export WLR_BACKENDS=headless
          export XDG_RUNTIME_DIR=/tmp
          export GDK_BACKEND=wayland
          export DBUS_SESSION_BUS_ADDRESS=

          mamba run -n startup-test cage python3 build-aux/appimage/testrun.py

      - name: Archive installer artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: appimage-${{ matrix.arch }}-package
          path: build-aux/appimage/build/*.AppImage

  windows:
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - arch: x86_64
            prefix: mingw-w64-clang-x86_64
            msystem: clang64
            platform: windows-latest
          - arch: arm64
            prefix: mingw-w64-clang-aarch64
            msystem: clangarm64
            platform: windows-11-arm
    runs-on: ${{ matrix.platform }}
    env:
      ARCH: ${{ matrix.arch }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup msys2
        uses: msys2/setup-msys2@e9898307ac31d1a803454791be09ab9973336e1c # v2.31.1
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            ${{ matrix.prefix }}-ca-certificates
            ${{ matrix.prefix }}-gettext-tools
            ${{ matrix.prefix }}-gobject-introspection
            ${{ matrix.prefix }}-gtk4
            ${{ matrix.prefix }}-libadwaita
            ${{ matrix.prefix }}-python-build
            ${{ matrix.prefix }}-python-cx-freeze
            ${{ matrix.prefix }}-python-gobject
            ${{ matrix.prefix }}-python-pycodestyle
            ${{ matrix.prefix }}-python-pylint
            ${{ matrix.prefix }}-python-setuptools
            ${{ matrix.prefix }}-python-wheel
            ${{ matrix.prefix }}-webp-pixbuf-loader

      - name: Install additional dependencies
        run: python3 build-aux/windows/dependencies.py

      - name: Freeze application
        run: python3 build-aux/windows/setup.py bdist_msi

      - name: Test application startup
        shell: cmd  # Exclude msys2 dependencies
        run: python3 build-aux/windows/testrun.py

      - name: Make package portable
        run: |
          mkdir build-aux/windows/build/package/Nicotine+/portable/
          cp build-aux/windows/readme-portable.txt build-aux/windows/build/package/Nicotine+/portable/README.txt

      - name: Archive installer artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: windows-${{ matrix.arch }}-installer
          path: build-aux/windows/build/*.msi

      - name: Archive portable artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: windows-${{ matrix.arch }}-portable
          path: build-aux/windows/build/package

  macos:
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - arch: x86_64
            platform: macos-26-intel
          - arch: arm64
            platform: macos-26
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Miniforge
        run: |
          wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
          bash "Miniforge3-$(uname)-$(uname -m).sh" -b -p "$HOME/miniforge3"
          echo "$HOME/miniforge3/bin" >> "$GITHUB_PATH"

      - name: Set up environment
        run: |
          mamba create -n nicotine-plus
          mamba create -n startup-test
          mamba run -n nicotine-plus python3 build-aux/macos/dependencies.py

      - name: Freeze application
        run: mamba run -n nicotine-plus python3 build-aux/macos/setup.py bdist_dmg

      - name: Test application startup
        run: mamba run -n startup-test python3 build-aux/macos/testrun.py

      - name: Archive installer artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: macos-${{ matrix.arch }}-installer
          path: build-aux/macos/build/*.dmg

  checksums:
    needs: [python-dist, debian, flatpak, snap, appimage, windows, macos]
    runs-on: ubuntu-slim
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/
          skip-decompress: true
          merge-multiple: true

      - name: Generate checksums
        run: python data/scripts/generate_sha256_checksums.py

      - name: Verify checksums
        run: cd dist && sha256sum --check ./*.sha256

      - name: Verify list of artifacts
        run: |
          cd dist
          ls \
            appimage-x86_64-package.zip \
            appimage-x86_64-package.zip.sha256 \
            debian-package.zip \
            debian-package.zip.sha256 \
            flatpak-aarch64-package.zip \
            flatpak-aarch64-package.zip.sha256 \
            flatpak-x86_64-package.zip \
            flatpak-x86_64-package.zip.sha256 \
            macos-arm64-installer.zip \
            macos-arm64-installer.zip.sha256 \
            macos-x86_64-installer.zip \
            macos-x86_64-installer.zip.sha256 \
            python-dist.zip \
            python-dist.zip.sha256 \
            snap-arm64-package.zip \
            snap-arm64-package.zip.sha256 \
            snap-x86_64-package.zip \
            snap-x86_64-package.zip.sha256 \
            windows-arm64-installer.zip \
            windows-arm64-installer.zip.sha256 \
            windows-arm64-portable.zip \
            windows-arm64-portable.zip.sha256 \
            windows-x86_64-installer.zip \
            windows-x86_64-installer.zip.sha256 \
            windows-x86_64-portable.zip \
            windows-x86_64-portable.zip.sha256

      - name: Archive installer artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: checksums
          path: dist/*.sha256

  attestation:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: checksums
    runs-on: ubuntu-slim
    timeout-minutes: 15
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/
          skip-decompress: true
          merge-multiple: true

      - name: Extract checksums
        run: cd dist && unzip checksums.zip

      - name: Attest
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: dist/

  metadata:
    needs: checksums
    runs-on: ubuntu-slim
    timeout-minutes: 15
    outputs:
      version: ${{ steps.version.outputs.version }}
      notes: ${{ steps.notes.outputs.notes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Store version
        id: version
        run: |
          VERSION="$(python -m pynicotine --ci-version)"
          echo "::notice::Version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Store notes
        id: notes
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          NOTES="$(python data/scripts/extract_release_notes.py "$VERSION")"
          echo "Release notes: $NOTES"
          {
            echo "notes<<EOF"
            echo "$NOTES"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Validate version
        if: inputs.create_release
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Version is invalid. Expected format is X.Y.Z."
            exit 1
          fi

      - name: Validate notes
        if: inputs.create_release
        env:
          NOTES: ${{ steps.notes.outputs.notes }}
        run: |
          if [[ -z "$NOTES" ]]; then
            echo "::error::Notes cannot be empty."
            exit 1
          fi

  pypi-publish:
    if: |
      github.repository == 'nicotine-plus/nicotine-plus' &&
      github.event_name == 'workflow_dispatch' && inputs.create_release
    needs: [attestation, metadata]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: pypi
      url: https://pypi.org/p/nicotine-plus
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: python-dist
          path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0

  github-release:
    if: github.event_name == 'workflow_dispatch' && inputs.create_release
    needs: [attestation, metadata]
    runs-on: ubuntu-slim
    timeout-minutes: 15
    environment:
      name: github-release
    permissions:
      contents: write
      discussions: write
    env:
      GITHUB_TOKEN: ${{ github.token }}
      VERSION: ${{ needs.metadata.outputs.version }}
      NOTES: ${{ needs.metadata.outputs.notes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/
          skip-decompress: true
          merge-multiple: true

      - name: Prepare release assets
        run: |
          cd dist
          unzip checksums.zip
          rm checksums.zip python-dist.*
          sha256sum --check ./*.sha256

      - name: Create release
        run: |
          gh release create "$VERSION" \
            --title "$VERSION" \
            --notes "$NOTES" \
            --target "$GITHUB_SHA" \
            --discussion-category "Releases" \
            dist/*
